version: "3"
volumes:
    data:
    logs:
    agent:
services:
  teamcity:
    image: jetbrains/teamcity-server
    volumes:
      - type: volume
        source: data
        target: /data/teamcity_server/datadir
      - type: volume
        source: logs
        target: /opt/teamcity/logs
    ports:
      - 8111:8111
  teamcity-agent:
    image: jetbrains/teamcity-agent
    privileged: true
    depends_on:
      - teamcity
    volumes:
      - type: volume
        source : agent
        target: /data/teamcity_agent/conf
    environment:
      SERVER_URL: "http://teamcity:8111"

